# Generated by Django 5.0.6 on 2024-05-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0003_alter_supplier_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='network_level',
        ),
        migrations.AddField(
            model_name='supplier',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='Уровень поставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='network_type',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], default=0, verbose_name='Тип сети'),
        ),
    ]
